name: 'action-pr-check'
description: 'action-pr-check'
inputs:
  branch:
    description: 'Current branch name'
    required: true
  token:
    description: 'Github Token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
