name: Test this action

on:
  pull_request:

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Test this action
        uses: ./
        with:
          branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
