name: Test this action

on:
  pull_request:

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: yarn
        run: yarn

      - name: build
        run: yarn build

      - name: Test this action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
